### ISSUE TITLE
Doesn't build if compiler doesn't use c++11 (or higher) by default

### ISSUE THREAD

**Issue by giuliomoro** [jujudusud/BPD#12]
e.g.: it does not build on macos 10.11.6 El Capitan, using the default `c++`

**Comment by jujudusud** [comment]
Hello @giuliomoro !
Thanks a lot for the PR.
Please consider that this repository is in progress !
Only 'test' branch is up to date for now and only vtbdi~.pd is working for now.

**Comment by giuliomoro** [comment]
thanks for the information. `vtbdi~.pd` includes `[bpd-lampe~]`, shall I assume that `[bpd-lampe~]` also works fine? It seems to work for me indeed!

**Comment by jpcima** [comment]
@giuliomoro yes, `bpd-lampe~` is fine, and so are most of faust-based parts in present state.

Project's goal is to construct a bass effect by assembly of smaller elements.
The faust parts are for discretization of parts of analog elements. `bpd-lampe~` has the tube distortions from `tubes.lib` of faust2. Filters were made from schematics using excellent DK simulator toolset from Guitarix.

In recent commits, I also pushed a tool `faust2pdex`. It's an alternative generator of externals which cares less about the UI, and has some choice how to lay out the inlets and other things.

**Comment by jujudusud** [comment]
I will write a readme about this in ./tools/faust2pdex as soon as possible.
